kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: grafana-cluster

networking:
  apiServerAddress: "127.0.0.1"
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 3030
        protocol: TCP
  - role: worker
  - role: worker
